replicaCount: 1

image:
  repository: mongo
  tag: "4.4"
  pullPolicy: IfNotPresent

service:
  port: 27017

# Override common values as needed for this chart
environment:
  name: dev
  clusterId: "000000"
  sdlcEnviroment: dev

application:
  type: Database
  cmdb:
    applicationID: MONGO001
    applicationName: "mongodb"
  environmentVariables:
    APPLICATION_NAME: "mongodb"
