environment:
  name: dev
  sdlc: dev

application:
  type: Database
  cmdb:
    applicationID: MONGO001
    applicationName: "mongodb"
  environmentVariables:
    APPLICATION_NAME: "mongodb"

registry:
  url: "docker.io"
  image:
    repository: "mongo"
    tag: "6.0"
    imagePullSecrets: []
  pullPolicy: IfNotPresent

deployment:
  replicas: 1
  containers:
    - name: mongo
      ports:
        - name: mongo
          containerPort: 27017
          protocol: TCP
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 1000
      livenessProbe:
        tcpSocket:
          port: mongo
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: mongo
        initialDelaySeconds: 5
        periodSeconds: 10
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
      volumeMounts:
        - name: data
          mountPath: /data/db
      env: []
  initContainers: []
  # Define a volume that uses the PVC created by the persistence block
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mongodb-pvc
  nodeSelector: {}
  affinity: {}
  tolerations: {}

service:
  enabled: true
  type: ClusterIP
  port: 27017
  targetPort: 27017
  protocol: TCP

persistence:
  enabled: true
  mountPath: /data/db
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""
  annotations: {}
