# MongoDB-specific configuration

image:
  repository: mongo
  tag: "4.4.6"
  pullPolicy: IfNotPresent

service:
  port: 27017

environment: 
  name: dev
  sdlc:  dev
application:
  type: Database
  cmdb:
    applicationID: MONGO001
    applicationName: "mongodb"
  environmentVariables:
    APPLICATION_NAME: "mongodb"

deployment:
  replicas: 1                     # Replica count is now defined under the deployment section
  containers:
    - name: mongo
      ports:
        - name: mongo
          containerPort: 27017
          protocol: TCP
      livenessProbe:
        tcpSocket:
          port: mongo
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: mongo
        initialDelaySeconds: 5
        periodSeconds: 10
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
      volumeMounts: []
      env: []
  initContainers: []
  volumes: []
  nodeSelector: {}
  affinity: {}
  tolerations: []

persistence:
  enabled: false
  mountPath: /data/db
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""
  annotations: {}
