{{- define "common.service" -}}
{{- if and .Values.service (eq .Values.service.enabled true) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-svc
  labels: {{ include "common.combinedLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: http
  selector:
    app: {{ include "common.fullname" . }}
{{- end }}
{{- end }}
