{{- include "common.validation" . | indent 0 }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}-deployment
  labels:
    {{ include "common.standardLabels" . | indent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ include "common.fullname" . }}
  template:
    metadata:
      labels:
        {{ include "common.standardLabels" . | indent 8 }}
    spec:
      containers:
{{- range .Values.deployment.containers }}
        - name: {{ .name }}
          image: "{{ $.Values.registry.url }}/{{ $.Values.registry.image.repository }}:{{ $.Values.registry.image.tag }}"
          ports:
{{- range .ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
{{- end }}
          livenessProbe:
{{ toYaml .livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .readinessProbe | indent 12 }}
          resources:
{{ toYaml .resources | indent 12 }}
          volumeMounts:
{{ toYaml .volumeMounts | indent 12 }}
          env:
{{ toYaml .env | indent 12 }}
          securityContext:
{{ toYaml .securityContext | indent 12 }}
{{- end }}
      initContainers:
{{ toYaml .Values.deployment.initContainers | indent 6 }}
      volumes:
{{ toYaml .Values.deployment.volumes | indent 6 }}
      nodeSelector:
{{ toYaml .Values.deployment.nodeSelector | indent 6 }}
      affinity:
{{ toYaml .Values.deployment.affinity | indent 6 }}
      tolerations:
{{ toYaml .Values.deployment.tolerations | indent 6 }}
