{{- if .Values.secrets.kubernetes.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-secret
  labels:
{{ include "common.standardLabels" . | nindent 4 }}
  {{- if .Values.secrets.kubernetes.annotations }}
  annotations:
{{ toYaml .Values.secrets.kubernetes.annotations | indent 4 }}
  {{- end }}
type: Opaque
data:
{{ toYaml .Values.secrets.kubernetes.data | indent 2 }}
{{- else if .Values.secrets.secretmanager.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "common.fullname" . }}-secret
  labels:
    {{ include "common.standardLabels" . | indent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.secretmanager.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.secrets.secretmanager.secretStoreRef.name | default "secretmanager-secret-store" | quote }}
    kind: ClusterSecretStore
  target:
    name: {{ include "common.fullname" . }}-secret
    creationPolicy: Owner
  data:
{{- range $key, $val := .Values.secrets.secretmanager.data }}
    - secretKey: {{ $key | quote }}
      remoteRef:
        key: {{ $val | quote }}
{{- end }}
{{- else if .Values.secrets.conjur.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "common.fullname" . }}-secret
  labels:
    {{ include "common.standardLabels" . | indent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.conjur.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.secrets.conjur.secretStoreRef.name | default "conjur-secret-store" | quote }}
    kind: SecretStore
  target:
    name: {{ include "common.fullname" . }}-secret
    creationPolicy: Owner
  data:
{{- range $key, $val := .Values.secrets.conjur.data }}
    - secretKey: {{ $key | quote }}
      remoteRef:
        key: {{ $val | quote }}
{{- end }}
{{- end }}
