# Kafka-specific configuration

image:
  repository: "confluentinc/cp-kafka"
  tag: "5.5.0"
  pullPolicy: IfNotPresent

service:
  port: 9092

environment: dev

application:
  type: Service
  cmdb:
    applicationID: KAFKA001
    applicationName: "kafka"
  environmentVariables:
    APPLICATION_NAME: "kafka"

deployment:
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "400m"
  # Environment variables to configure Kafka
  env:
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zookeeper:2181"
  nodeSelector: {}
  affinity: {}
  tolerations: {}

persistence:
  enabled: false
  mountPath: /var/lib/kafka/data
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: ""
  annotations: {}
